---

ansible_user: "{{ vault_ansible_user }}"
ansible_become_pass: "{{ vault_ansible_become_pass }}"

default_user: pi
default_group: pi

clear_root_history: true
enable_ntpd_at_boot: true
start_ntpd_immediately: true

desktop: "i3"

# fenrir installation variables
enable_fenrir_at_boot: false
start_fenrir_immediately: false


# Setting variables for /etc/fenrirscreenreader/settings/settings.conf
fenrir_sound_volume: 1.0
fenrir_speech_rate: 0.40
fenrir_speech_voice: 'm1'
fenrir_speech_language: 'english-us'



