---

ansible_user: "{{ vault_ansible_user }}"
ansible_become_pass: "{{ vault_ansible_become_pass }}"

default_user: alarm
default_group: alarm


default_locale: "en_US.UTF-8"

locales:
  - "en_US.UTF-8"

timezone: "America/Chicago"

console_keymap: "us"

clear_root_history: true

# fenrir installation variables
enable_fenrir_at_boot: false
start_fenrir_immediately: false


# Setting variables for /etc/fenrirscreenreader/settings/settings.conf
fenrir_sound_volume: 1.0
fenrir_speech_rate: 0.40
fenrir_speech_voice: 'm1'
fenrir_speech_language: 'english-us'



