---

default_user: pi
default_group: pi


#
# Below here are lots of settings for putting into
# the fenrir configuration file templates
#

# Setting variables for /etc/fenrirscreenreader/settings/settings.conf
fenrir_sound_enabled: true
fenrir_sound_driver: 'genericDriver'
fenrir_sound_theme: 'default'
fenrir_sound_volume: 1.0
fenrir_sound_genericPlayFileCommand: 'fix this'
fenrir_sound_genericFrequencyCommand: 'fix this'

fenrir_speech_enabled: true
fenrir_speech_driver: 'genericDriver'
fenrir_speech_serverPath: '/usr/local/src/emacspeak/servers/native-espeak'
fenrir_speech_rate: 0.65
fenrir_speech_pitch: 0.5
fenrir_speech_capitalPitch: 0.9
fenrir_speech_volume: 1.0
fenrir_speech_module: 'espeak'
fenrir_speech_voice: 'en-us'
fenrir_speech_language: 'english-us'
fenrir_speech_autoReadIncoming: true
fenrir_speech_genericSpeachCommand: 'fix this'
fenrir_speech_MinVolume: 0
fenrir_speech_MaxVolume: 200
fenrir_speech_MinPitch: 0
fenrir_speech_MaxPitch: 99
fenrir_speech_MinRate: 80
fenrir_speech_MaxRate: 450

fenrir_braille_enabled: true
fenrir_braille_driver: 'dummyDriver'
fenrir_braille_layout: 'en'
fenrir_braille_FlushMode: 'word'
fenrir_braille_flushTimeout: 3
fenrir_braille_cursorFocusMode: 'page'
fenrir_braille_fixCursorOnCell: -1
fenrir_braille_cursorFollowMode: 'review'
fenrir_braille_panSizeHorizontal: 0

fenrir_screen_driver: 'vcsaDriver'
fenrir_screen_encoding: 'auto'
fenrir_screen_updateDelay: 0.05
fenrir_screen_suspendingScreen: ''
fenrir_screen_autoDetectSuspendingScreen: true

fenrir_keyboard_driver: 'evdevDriver'
fenrir_keyboard_device: 'ALL'
fenrir_keyboard_grabDevices: true
fenrir_keyboard_ignoreShortcuts: false
fenrir_keyboard_keyboardLayout: 'desktop'
fenrir_keyboard_charEcho: true
fenrir_keyboard_charDeleteEcho: true
fenrir_keyboard_wordEcho: false
fenrir_keyboard_interruptOnKeyPress: true
fenrir_keyboard_interruptOnKeyPressFilter: ''
fenrir_keyboard_doubleTapTimeout: 0.2

fenrir_general_debugLevel: 0
fenrir_general_debugMode: 'File'
fenrir_general_debugFile: '/var/log/fenrirscreenreader/fenrir.log'
fenrir_general_punctuationProfile: 'default'
fenrir_general_punctuationLevel: 'some'
fenrir_general_respectPunctuationPause: true
fenrir_general_newLinePause: true
fenrir_general_numberOfClipBoards: 10
fenrir_general_clipboardExportPath: '/home/$user/.fenrirClipboard'
fenrir_general_emoticons: true
fenrir_general_fenrirKeys: 'KEY_KP0,KEY_META,KEY_INSERT'
fenrir_general_scriptKey: 'KEY_COMPOSE'
fenrir_general_timeFormat: '%H:%M:%P'
fenrir_general_dateFormat: '%A, %B %d, %Y'
fenrir_general_autoSpellCheck: true
fenrir_general_spellCheckLanguage: 'en_US'
fenrir_general_scriptPath: '/usr/share/fenrirscreenreader/scripts'
fenrir_general_commandPath: ''
fenrir_general_attributeFormatString: 'Background fenrirBGColor,Foreground fenrirFGColor,fenrirUnderline,fenrirBold,fenrirBlink, Font fenrirFont,Fontsize fenrirFontSize'
fenrir_general_autoPresentIndent: true
fenrir_general_hasAttributes: true
fenrir_general_shell: ''

fenrir_focus_cursor: true
fenrir_focus_highlight: false

fenrir_remote_enable: true
fenrir_remote_driver: 'unixDriver'
fenrir_remote_port: '22447'
fenrir_remote_socketpath: '/tmp/'
fenrir_remote_enableSettingsRemote: true
fenrir_remote_enableCommandRemote: true

fenrir_barrier_enabled: true
fenrir_barrier_leftBarriers: ''
fenrir_barrier_rightBarriers: ''

fenrir_review_lineBreak: true
fenrir_review_endOfScreen: true
fenrir_review_leaveReviewOnCursorChange: true
fenrir_review_leaveReviewOnScreenChange: true

fenrir_promote_enabled: true
fenrir_promote_inactiveTimeoutSec: 120
fenrir_promote_list: ''

fenrir_time_enabled: false
fenrir_time_presentTime: true
fenrir_time_presentDate: true
fenrir_time_delaySec: 0
fenrir_time_onMinutes: '00,30'
fenrir_time_announce: true
fenrir_time_interrupt: false


# Setting variables for /etc/fenrirscreenreader/settings/settings-daemon.conf
fenrir_daemon_sound_enabled: true
fenrir_daemon_sound_driver: 'genericDriver'
fenrir_daemon_sound_theme: 'default'
fenrir_daemon_sound_volume: 1.0
fenrir_daemon_sound_genericPlayFileCommand: 'fix this'
fenrir_daemon_sound_genericFrequencyCommand: 'fix this'

fenrir_daemon_speech_enabled: true
fenrir_daemon_speech_driver: 'genericDriver'
fenrir_daemon_speech_serverPath: '/usr/local/src/emacspeak/servers/native-espeak'
fenrir_daemon_speech_rate: 0.65
fenrir_daemon_speech_pitch: 0.5
fenrir_daemon_speech_capitalPitch: 0.9
fenrir_daemon_speech_volume: 1.0
fenrir_daemon_speech_module: 'espeak'
fenrir_daemon_speech_voice: 'en-us'
fenrir_daemon_speech_language: 'english-us'
fenrir_daemon_speech_autoReadIncoming: true
fenrir_daemon_speech_genericSpeachCommand: 'fix this'
fenrir_daemon_speech_MinVolume: 0
fenrir_daemon_speech_MaxVolume: 200
fenrir_daemon_speech_MinPitch: 0
fenrir_daemon_speech_MaxPitch: 99
fenrir_daemon_speech_MinRate: 80
fenrir_daemon_speech_MaxRate: 450

fenrir_daemon_braille_enabled: false
fenrir_daemon_braille_driver: 'dummyDriver'
fenrir_daemon_braille_layout: 'en'
fenrir_daemon_braille_FlushMode: 'word'
fenrir_daemon_braille_flushTimeout: 3
fenrir_daemon_braille_cursorFocusMode: 'page'
fenrir_daemon_braille_fixCursorOnCell: -1
fenrir_daemon_braille_cursorFollowMode: 'review'
fenrir_daemon_braille_panSizeHorizontal: 0

fenrir_daemon_screen_driver: 'vcsaDriver'
fenrir_daemon_screen_encoding: 'auto'
fenrir_daemon_screen_updateDelay: 0.05
fenrir_daemon_screen_suspendingScreen: ''
fenrir_daemon_screen_autoDetectSuspendingScreen: true

fenrir_daemon_keyboard_driver: 'evdevDriver'
fenrir_daemon_keyboard_device: 'ALL'
fenrir_daemon_keyboard_grabDevices: true
fenrir_daemon_keyboard_ignoreShortcuts: false
fenrir_daemon_keyboard_keyboardLayout: 'desktop'
fenrir_daemon_keyboard_charEcho: true
fenrir_daemon_keyboard_charDeleteEcho: true
fenrir_daemon_keyboard_wordEcho: false
fenrir_daemon_keyboard_interruptOnKeyPress: true
fenrir_daemon_keyboard_interruptOnKeyPressFilter: ''
fenrir_daemon_keyboard_doubleTapTimeout: 0.2

fenrir_daemon_general_debugLevel: 0
fenrir_daemon_general_debugMode: 'File'
fenrir_daemon_general_debugFile: '/var/log/fenrirscreenreader/fenrir.log'
fenrir_daemon_general_punctuationProfile: 'default'
fenrir_daemon_general_punctuationLevel: 'some'
fenrir_daemon_general_respectPunctuationPause: true
fenrir_daemon_general_newLinePause: true
fenrir_daemon_general_numberOfClipBoards: 10
fenrir_daemon_general_clipboardExportPath: '/home/$user/.fenrirClipboard'
fenrir_daemon_general_emoticons: true
fenrir_daemon_general_fenrirKeys: 'KEY_KP0,KEY_META,KEY_INSERT'
fenrir_daemon_general_scriptKey: 'KEY_COMPOSE'
fenrir_daemon_general_timeFormat: '%H:%M:%P'
fenrir_daemon_general_dateFormat: '%A, %B %d, %Y'
fenrir_daemon_general_autoSpellCheck: true
fenrir_daemon_general_spellCheckLanguage: 'en_US'
fenrir_daemon_general_scriptPath: '/usr/share/fenrirscreenreader/scripts'
fenrir_daemon_general_commandPath: ''
fenrir_daemon_general_attributeFormatString: 'Background fenrirBGColor,Foreground fenrirFGColor,fenrirUnderline,fenrirBold,fenrirBlink, Font fenrirFont,Fontsize fenrirFontSize'
fenrir_daemon_general_autoPresentIndent: true
fenrir_daemon_general_hasAttributes: true
fenrir_daemon_general_shell: ''

fenrir_daemon_focus_cursor: true
fenrir_daemon_focus_highlight: false

fenrir_daemon_remote_enable: true
fenrir_daemon_remote_driver: 'unixDriver'
fenrir_daemon_remote_port: '22447'
fenrir_daemon_remote_socketpath: '/tmp/'
fenrir_daemon_remote_enableSettingsRemote: true
fenrir_daemon_remote_enableCommandRemote: true

fenrir_daemon_barrier_enabled: true
fenrir_daemon_barrier_leftBarriers: ''
fenrir_daemon_barrier_rightBarriers: ''

fenrir_daemon_review_lineBreak: true
fenrir_daemon_review_endOfScreen: true
fenrir_daemon_review_leaveReviewOnCursorChange: true
fenrir_daemon_review_leaveReviewOnScreenChange: true

fenrir_daemon_promote_enabled: true
fenrir_daemon_promote_inactiveTimeoutSec: 120
fenrir_daemon_promote_list: ''

fenrir_daemon_time_enabled: false
fenrir_daemon_time_presentTime: true
fenrir_daemon_time_presentDate: true
fenrir_daemon_time_delaySec: 0
fenrir_daemon_time_onMinutes: '00,30'
fenrir_daemon_time_announce: true
fenrir_daemon_time_interrupt: false


# Setting variables for /etc/fenrirscreenreader/settings/settings-pty.conf
fenrir_pty_sound_enabled: true
fenrir_pty_sound_driver: 'genericDriver'
fenrir_pty_sound_theme: 'default'
fenrir_pty_sound_volume: 1.0
fenrir_pty_sound_genericPlayFileCommand: 'fix this'
fenrir_pty_sound_genericFrequencyCommand: 'fix this'

fenrir_pty_speech_enabled: true
fenrir_pty_speech_driver: 'genericDriver'
fenrir_pty_speech_serverPath: '/usr/local/src/emacspeak/servers/native-espeak'
fenrir_pty_speech_rate: 0.65
fenrir_pty_speech_pitch: 0.5
fenrir_pty_speech_capitalPitch: 0.9
fenrir_pty_speech_volume: 1.0
fenrir_pty_speech_module: 'espeak'
fenrir_pty_speech_voice: 'en-us'
fenrir_pty_speech_language: 'english-us'
fenrir_pty_speech_autoReadIncoming: true
fenrir_pty_speech_genericSpeachCommand: 'fix this'
fenrir_pty_speech_MinVolume: 0
fenrir_pty_speech_MaxVolume: 200
fenrir_pty_speech_MinPitch: 0
fenrir_pty_speech_MaxPitch: 99
fenrir_pty_speech_MinRate: 80
fenrir_pty_speech_MaxRate: 450

fenrir_pty_braille_enabled: false
fenrir_pty_braille_driver: 'dummyDriver'
fenrir_pty_braille_layout: 'en'
fenrir_pty_braille_FlushMode: 'word'
fenrir_pty_braille_flushTimeout: 3
fenrir_pty_braille_cursorFocusMode: 'page'
fenrir_pty_braille_fixCursorOnCell: -1
fenrir_pty_braille_cursorFollowMode: 'review'
fenrir_pty_braille_panSizeHorizontal: 0

fenrir_pty_screen_driver: 'vcsaDriver'
fenrir_pty_screen_encoding: 'auto'
fenrir_pty_screen_updateDelay: 0.05
fenrir_pty_screen_suspendingScreen: ''
fenrir_pty_screen_autoDetectSuspendingScreen: true

fenrir_pty_keyboard_driver: 'evdevDriver'
fenrir_pty_keyboard_device: 'ALL'
fenrir_pty_keyboard_grabDevices: true
fenrir_pty_keyboard_ignoreShortcuts: false
fenrir_pty_keyboard_keyboardLayout: 'desktop'
fenrir_pty_keyboard_charEcho: true
fenrir_pty_keyboard_charDeleteEcho: true
fenrir_pty_keyboard_wordEcho: false
fenrir_pty_keyboard_interruptOnKeyPress: true
fenrir_pty_keyboard_interruptOnKeyPressFilter: ''
fenrir_pty_keyboard_doubleTapTimeout: 0.2

fenrir_pty_general_debugLevel: 0
fenrir_pty_general_debugMode: 'File'
fenrir_pty_general_debugFile: '/var/log/fenrirscreenreader/fenrir.log'
fenrir_pty_general_punctuationProfile: 'default'
fenrir_pty_general_punctuationLevel: 'some'
fenrir_pty_general_respectPunctuationPause: true
fenrir_pty_general_newLinePause: true
fenrir_pty_general_numberOfClipBoards: 10
fenrir_pty_general_clipboardExportPath: '/home/$user/.fenrirClipboard'
fenrir_pty_general_emoticons: true
fenrir_pty_general_fenrirKeys: 'KEY_KP0,KEY_META,KEY_INSERT'
fenrir_pty_general_scriptKey: 'KEY_COMPOSE'
fenrir_pty_general_timeFormat: '%H:%M:%P'
fenrir_pty_general_dateFormat: '%A, %B %d, %Y'
fenrir_pty_general_autoSpellCheck: true
fenrir_pty_general_spellCheckLanguage: 'en_US'
fenrir_pty_general_scriptPath: '/usr/share/fenrirscreenreader/scripts'
fenrir_pty_general_commandPath: ''
fenrir_pty_general_attributeFormatString: 'Background fenrirBGColor,Foreground fenrirFGColor,fenrirUnderline,fenrirBold,fenrirBlink, Font fenrirFont,Fontsize fenrirFontSize'
fenrir_pty_general_autoPresentIndent: true
fenrir_pty_general_hasAttributes: true
fenrir_pty_general_shell: ''

fenrir_pty_focus_cursor: true
fenrir_pty_focus_highlight: false

fenrir_pty_remote_enable: true
fenrir_pty_remote_driver: 'unixDriver'
fenrir_pty_remote_port: '22447'
fenrir_pty_remote_socketpath: '/tmp/'
fenrir_pty_remote_enableSettingsRemote: true
fenrir_pty_remote_enableCommandRemote: true

fenrir_pty_barrier_enabled: true
fenrir_pty_barrier_leftBarriers: ''
fenrir_pty_barrier_rightBarriers: ''

fenrir_pty_review_lineBreak: true
fenrir_pty_review_endOfScreen: true
fenrir_pty_review_leaveReviewOnCursorChange: true
fenrir_pty_review_leaveReviewOnScreenChange: true

fenrir_pty_promote_enabled: true
fenrir_pty_promote_inactiveTimeoutSec: 120
fenrir_pty_promote_list: ''

fenrir_pty_time_enabled: false
fenrir_pty_time_presentTime: true
fenrir_pty_time_presentDate: true
fenrir_pty_time_delaySec: 0
fenrir_pty_time_onMinutes: '00,30'
fenrir_pty_time_announce: true
fenrir_pty_time_interrupt: false


