---

- hosts: alarmpi
  become: yes
  gather_facts: yes
  roles:
    - fenrir


#    - brltty
#    - locale
#    - yaourt
#    - console
#    - extras
#    - kpartx
#    - rpi_image_tool
#    - history
