---

- name: Import tasks from dependencies.yml
  import_tasks: dependencies.yml


- name: Import tasks from build.yml
  import_tasks: build.yml


- name: Import tasks from config.yml
  import_tasks: config.yml


